const actionTypes ={
    LOGIN:'LOGIN',
    LOGIN_FAIL :'LOGIN_FAIL',
    LOGIN_SUCCSCESS :'LOGIN_SUCCSCESS',
    REGISTER_SUCCESS: 'REGISTER_SUCCSCESS',
    REGISTER_FAIL :'REGISTER_FAIL',
    LOGOUT: 'LOGUOT',


    GET_POSTS: "GET_POST" 
}

export default actionTypes