const actionTypes ={
    LOGIN:'LOGIN',
    LOGIN_FAIL :'LOGIN_FAIL',
    LOGIN_SUCCSCESS :'LOGIN_SUCCSCESS',
    REGISTER_SUCCESS: 'REGISTER_SUCCSCESS',
    REGISTER_FAIL :'REGISTER_FAIL',
    LOGOUT: 'LOGUOT',


    GET_POSTS: "GET_POST" ,
    GET_POST_LIMIT: "GET_POST_LIMIT",
    GET_POST_ADMIN: "GET_POST_ADMIN",
    GET_NEW_POST: "GET_NEW_POST",

    GET_CATEGORIES : "GET_CATEGORIES",
    GET_PRICES : "GET_PRICES",
    GET_AREAS : "GET_AREAS",
    GET_PROVINCE : "GET_PROVINCE",

    //USER
    GET_CURRENT : 'GET_CURRENT', 
}

export default actionTypes